### ISSUE TITLE
Incompatible with CraftTweaker recipes

### ISSUE THREAD

**Issue by Sunconure11** [xanthian/variantcomposters#1]
Due to how you handle recipes, this mod is inherently incompatible with CraftTweaker's compost recipes.

@jaredlll08 can explain more in detail.

**Comment by Sunconure11** [comment]
This may also affect some of your other mods too, albeit in other ways. I suggest looking them over.

**Comment by xanthian** [comment]
No other way to do it I'm afraid. So probably wont change it.
Unless CraftTweaker dev has an ingenious way of doing this.

**Comment by jaredlll08** [comment]
I'm not actually sure why this wouldn't be working, so for starters the actual issue is adding new compostables, which in CraftTweaker is done like so:
```zenscript
composter.setValue(<item:immersive_weathering:ivy>, 0.15);
composter.setValue(<item:immersive_weathering:weeds>, 0.15);
```
That simply adds to the `net.minecraft.block.ComposterBlock#CHANCES` map, which since you extend `ComposterBlock`, it should continue using right?

> No other way to do it I'm afraid. So probably wont change it.

I'm assuming you are talking about this piece of code:
https://github.com/xanthian/variantcomposters/blob/1.19/src/main/java/net/xanthian/variantcomposters/mixin/RecipeManagerMixin.java#L26-L29

There shouldn't be any issue for CraftTweaker to change those recipes as we run long after your mixin is applied.

**Comment by xanthian** [comment]
Ah this is 1.19.
As of 1.20 I wont be using the recipe mixin anyway.

**Comment by xanthian** [comment]
Also, please elaborate on what / how its incompatible

**Comment by jaredlll08** [comment]
I believe the incompatibility is that setting new compostables doesn't actually do anything, I have not confirmed this, just going on what Sunconure11 has said.

Saying that, I don't see how this would be an issue on your side, my current guess is that another mod is messing with it.

**Comment by Sunconure11** [comment]
Issue is also present when trying to do it with KubeJS.

**Comment by xanthian** [comment]
so a new plant/tree/food cannot be composted in the composters I add??
not sure how thats an issue on my side tbh, my composters extend ComposterBlock and dont do anything fancy other than copy the settings from the vanilla Composter
@Sunconure11 Can you elaborate further please, with error/screenshots where possible

**Comment by Sunconure11** [comment]
We've come to the general conclusion that your mod is not at fault, but the bug is that stuff added in via CraftTweaker or KubeJS won't go into a composter.
